/**
 * Core data model for a Buttery Stitches project.
 *
 * IMPORTANT: every coordinate and dimension in this model is in **millimeters**.
 * We only convert to pyembroidery's 1/10 mm units at the moment of export
 * (see lib/export). Keeping the in-app model in mm keeps the geometry and
 * stitch-math code readable and unit-test friendly.
 */

/** The three stitch primitives the engine knows how to generate. */
export type StitchType = "running" | "satin" | "fill";

/** A polyline / polygon in millimeter coordinates. */
export type Point = { x: number; y: number };
export type Path = Point[];

export interface EmbObjectParams {
  /** running: mm between needle penetrations (default 2.5). */
  stitchLength?: number;
  /** fill/satin: mm between rows (default 0.4). */
  density?: number;
  /** fill direction in degrees (default 0). */
  angle?: number;
  /** add a stabilizing underlay pass (default true for fill/satin). */
  underlay?: boolean;
  /** mm added to satin width to compensate for fabric pull (default 0.2). */
  pullComp?: number;
  /** draw the object's border outline in the editor (default true). */
  outline?: boolean;
  /** how a fill is stitched: tatami (broad areas) or satin columns (lettering). */
  fillStyle?: "tatami" | "satin";
}

/** Re-edit metadata for objects generated by the text tool. */
export interface TextSpec {
  content: string;
  fontId: string;
  heightMm: number;
  letterSpacingMm: number;
}

export interface EmbObject {
  id: string;
  name: string;
  type: StitchType;
  /** references a ThreadColor.id */
  colorId: string;
  /**
   * mm coordinates.
   *  - fill:    one or more closed polygons (first = outer, rest = holes).
   *  - satin:   exactly two paths forming a rail pair (left, right).
   *  - running: one open polyline.
   */
  paths: Path[];
  params: EmbObjectParams;
  visible: boolean;
  /** present on text objects so they can be re-edited (double-click). */
  text?: TextSpec;
}

export interface ThreadColor {
  id: string;
  rgb: [number, number, number];
  /** e.g. "Madeira Polyneon" */
  brand?: string;
  /** thread catalog number */
  code?: string;
  name?: string;
}

export interface Hoop {
  wMm: number;
  hMm: number;
  name: string;
}

/** What the design is stitched onto — modifies density, pull-comp, and underlay. */
export type FabricType = "woven" | "knit" | "pile" | "sheer";

/** How a fabric bends the stitch parameters (see docs/stitch-logic.md §8). */
export interface FabricProfile {
  name: string;
  /** multiplies row density gap — <1 packs rows tighter (stretchy fabric). */
  densityMul: number;
  /** multiplies pull compensation — stretchy fabric pulls in more. */
  pullMul: number;
  /** how heavy the underlay should be. */
  underlay: "light" | "standard" | "heavy";
}

export const FABRICS: Record<FabricType, FabricProfile> = {
  woven: { name: "Woven (stable)", densityMul: 1.0, pullMul: 1.0, underlay: "standard" },
  knit: { name: "Knit / stretch", densityMul: 0.9, pullMul: 1.5, underlay: "heavy" },
  pile: { name: "Pile / fleece", densityMul: 0.85, pullMul: 1.2, underlay: "heavy" },
  sheer: { name: "Sheer / delicate", densityMul: 1.1, pullMul: 0.7, underlay: "light" },
};

export const DEFAULT_FABRIC: FabricType = "woven";

/** The profile for a project's fabric (defaults to woven when unset). */
export function fabricProfile(fabric: FabricType | undefined): FabricProfile {
  return FABRICS[fabric ?? DEFAULT_FABRIC];
}

export interface Project {
  version: 1;
  widthMm: number;
  heightMm: number;
  hoop: Hoop;
  /** what it's stitched onto (default "woven"); bends density/underlay/pull. */
  fabric?: FabricType;
  colors: ThreadColor[];
  /** ORDER = stitch sequence. The first object is stitched first. */
  objects: EmbObject[];
}

/** Default parameter values, applied wherever a param is omitted. */
export const DEFAULT_PARAMS: Required<EmbObjectParams> = {
  stitchLength: 2.5,
  density: 0.4,
  angle: 0,
  underlay: true,
  pullComp: 0.2,
  outline: true,
  fillStyle: "tatami",
};

/** Resolve an object's params against the defaults for the engine. */
export function resolveParams(
  type: StitchType,
  params: EmbObjectParams,
): Required<EmbObjectParams> {
  return {
    stitchLength: params.stitchLength ?? DEFAULT_PARAMS.stitchLength,
    density: params.density ?? DEFAULT_PARAMS.density,
    angle: params.angle ?? DEFAULT_PARAMS.angle,
    // running stitch never has underlay regardless of stored value
    underlay:
      type === "running" ? false : (params.underlay ?? DEFAULT_PARAMS.underlay),
    pullComp: params.pullComp ?? DEFAULT_PARAMS.pullComp,
    outline: params.outline ?? DEFAULT_PARAMS.outline,
    fillStyle: params.fillStyle ?? DEFAULT_PARAMS.fillStyle,
  };
}
