/**
 * Core data model for a Buttery Stitches project.
 *
 * IMPORTANT: every coordinate and dimension in this model is in **millimeters**.
 * We only convert to pyembroidery's 1/10 mm units at the moment of export
 * (see lib/export). Keeping the in-app model in mm keeps the geometry and
 * stitch-math code readable and unit-test friendly.
 */

/** The three stitch primitives the engine knows how to generate. */
export type StitchType = "running" | "satin" | "fill";

/** A polyline / polygon in millimeter coordinates. */
export type Point = { x: number; y: number };
export type Path = Point[];

/** A user-placed control node; `smooth` curves the path through it (vs a corner). */
export interface NodePt {
  x: number;
  y: number;
  smooth?: boolean;
}
export type NodePath = NodePt[];

export interface EmbObjectParams {
  /** running: mm between needle penetrations (default 2.5). */
  stitchLength?: number;
  /** running: passes over the line for a bold bean/triple stitch (0/1 = single,
   *  3/5/7 = bean). Default 0 (single). */
  beanRepeats?: number;
  /** running: emit the path's points verbatim (no resampling) — used for stitches
   *  imported from an embroidery file so they're preserved exactly. Default false. */
  raw?: boolean;
  /** fill/satin: mm between rows (default 0.4). */
  density?: number;
  /** fill: mm between penetrations ALONG a tatami row (default 4). Shorter =
   *  denser, more secure texture; longer = smoother sheen, fewer stitches. */
  fillStitchLength?: number;
  /** fill direction in degrees (default 0). */
  angle?: number;
  /** ABSOLUTE stitch grain (deg) painted by the user with the Direction tool. When
   *  set it overrides the auto grain and the turning/flow fills — the rows run
   *  straight at this angle. `null`/absent = auto direction (principal axis +
   *  `angle`). */
  directionDeg?: number | null;
  /** A flow curve painted with the Direction tool: the fill's rows run PERPENDICULAR
   *  to this curve, so the stitches follow it (a leaf vein, a cheek). Stored as
   *  points NORMALIZED to the object's bbox ([0..1]) so it moves/scales with the
   *  fill. Takes precedence over `directionDeg`; `null`/absent = not set. */
  flowPath?: [number, number][] | null;
  /** add a stabilizing underlay pass (default true for fill/satin). */
  underlay?: boolean;
  /** how heavy the underlay is. "auto" follows the fabric; the rest override it
   *  per object (light → just an edge, heavy → edge + zig-zag/criss-cross). */
  underlayWeight?: "auto" | "light" | "standard" | "heavy";
  /** mm added to satin width to compensate for fabric pull (default 0.2). */
  pullComp?: number;
  /** mm trimmed off each satin column end to compensate for lengthwise fabric
   *  push (default 0.2; open columns only). */
  pushComp?: number;
  /** draw the object's border outline in the editor (default true). */
  outline?: boolean;
  /** how a fill is stitched: tatami (broad areas), satin columns (lettering),
   *  contour (rows that echo the shape's outline), gradient (tatami whose row
   *  spacing ramps for a shaded/ombré effect), or motif (a tiled decorative
   *  motif). */
  fillStyle?: "tatami" | "satin" | "contour" | "gradient" | "motif" | "blend" | "field";
  /** LINE-ART: render this (satin) object's medial columns as clean RUNNING lines
   *  down their centerline rather than filled satin — for outlines and fine detail
   *  strokes (auto-set by the tracer on thin regions). */
  lineArt?: boolean;
  /** second thread color id for fillStyle "blend" (a two-thread ombré). The fill
   *  fades from the object's colorId to this across the shape. */
  blendColorId?: string;
  /** motif id for fillStyle "motif" (and the carve pattern). Default "wave". */
  motif?: string;
  /** motif cell size in mm for a motif fill (default 4). */
  motifSizeMm?: number;
  /** carve: a motif id carved into a tatami/gradient fill as un-penetrated relief
   *  grooves, or "none" (default). */
  carve?: string;
  /** running: repeat a motif along the line (decorative motif run), or "none". */
  motifRun?: string;
  /** appliqué: stitch the shape as placement run → STOP (lay fabric) → tackdown
   *  → STOP (trim) → satin cover, instead of a normal fill. Default false. */
  applique?: boolean;
}

/** Re-edit metadata for objects generated by the text tool. */
export interface TextSpec {
  content: string;
  fontId: string;
  heightMm: number;
  letterSpacingMm: number;
  /** line spacing as a multiple of letter height (multiline). Default 1.35. */
  lineSpacing?: number;
  /** arc bend in degrees: + arches up, − down, 0 straight. Default 0. */
  archDeg?: number;
  /** lay the text around a circle of this baseline radius (mm). Overrides arch. */
  circleRadiusMm?: number;
  /** which side of the circle ("top" = upper arc, "bottom" = upright lower arc). */
  circleSide?: "top" | "bottom";
  /** lay the text along this open polyline (mm). Overrides arch and circle. */
  pathMm?: Point[];
}

export interface EmbObject {
  id: string;
  name: string;
  type: StitchType;
  /** references a ThreadColor.id */
  colorId: string;
  /**
   * mm coordinates.
   *  - fill:    one or more closed polygons (first = outer, rest = holes).
   *  - satin:   exactly two paths forming a rail pair (left, right).
   *  - running: one open polyline.
   */
  paths: Path[];
  /** Optional explicit satin-column centerlines (mm, object space) — the per-glyph
   *  AUTHORED decomposition for the flagship font. When present on a satin fill,
   *  the engine lays a satin column down each centerline (rails raycast to the real
   *  outline) instead of auto-skeletonizing, so diagonal-junction glyphs (W, M, A,
   *  K, …) sew as clean strokes. Transformed alongside `paths`. */
  satinCenterlines?: Path[];
  /** Optional editable control nodes (one ring per `paths` ring) for corner↔curve
   *  editing. When present, `paths` is densified from these; the engine still only
   *  reads `paths`. Absent on imported/auto-digitized/satin objects. */
  nodes?: NodePath[];
  params: EmbObjectParams;
  visible: boolean;
  /** present on text objects so they can be re-edited (double-click). */
  text?: TextSpec;
  /** objects sharing a groupId select and move together. */
  groupId?: string;
}

export interface ThreadColor {
  id: string;
  rgb: [number, number, number];
  /** e.g. "Madeira Polyneon" */
  brand?: string;
  /** thread catalog number */
  code?: string;
  name?: string;
}

export interface Hoop {
  wMm: number;
  hMm: number;
  name: string;
}

/** What the design is stitched onto — modifies density, pull-comp, and underlay. */
export type FabricType = "woven" | "knit" | "pile" | "sheer";

/** How a fabric bends the stitch parameters (see docs/stitch-logic.md §8). */
export interface FabricProfile {
  name: string;
  /** multiplies row density gap — <1 packs rows tighter (stretchy fabric). */
  densityMul: number;
  /** multiplies pull compensation — stretchy fabric pulls in more. */
  pullMul: number;
  /** how heavy the underlay should be. */
  underlay: "light" | "standard" | "heavy";
  /** multiplies stitch length — pile rides longer stitches above the loops. */
  stitchLenMul: number;
}

export const FABRICS: Record<FabricType, FabricProfile> = {
  woven: { name: "Woven (stable)", densityMul: 1.0, pullMul: 1.0, underlay: "standard", stitchLenMul: 1.0 },
  knit: { name: "Knit / stretch", densityMul: 0.9, pullMul: 1.5, underlay: "heavy", stitchLenMul: 1.0 },
  pile: { name: "Pile / fleece", densityMul: 0.85, pullMul: 1.2, underlay: "heavy", stitchLenMul: 1.15 },
  sheer: { name: "Sheer / delicate", densityMul: 1.1, pullMul: 0.7, underlay: "light", stitchLenMul: 1.0 },
};

export const DEFAULT_FABRIC: FabricType = "woven";

/** The profile for a project's fabric (defaults to woven when unset). */
export function fabricProfile(fabric: FabricType | undefined): FabricProfile {
  return FABRICS[fabric ?? DEFAULT_FABRIC];
}

/**
 * Thread weight (the "wt" number on the spool). Thinner thread (higher number)
 * lays a narrower line, so rows must pack tighter to cover; thicker thread opens
 * up. 40wt is the industry standard baseline.
 */
export type ThreadWeight = 30 | 40 | 60;

export const DEFAULT_THREAD_WEIGHT: ThreadWeight = 40;

/** Row-spacing multiplier for a thread weight (≈ −28% gap for fine 60wt,
 *  +15% for bold 30wt). Multiplies the density gap, so <1 = denser rows. */
export function threadDensityMul(weight: ThreadWeight | undefined): number {
  switch (weight ?? DEFAULT_THREAD_WEIGHT) {
    case 60:
      return 0.72;
    case 30:
      return 1.15;
    default:
      return 1.0;
  }
}

export interface Project {
  version: 1;
  widthMm: number;
  heightMm: number;
  hoop: Hoop;
  /** what it's stitched onto (default "woven"); bends density/underlay/pull. */
  fabric?: FabricType;
  /** thread weight (default 40wt); bends row density to keep coverage. */
  threadWeight?: ThreadWeight;
  colors: ThreadColor[];
  /** ORDER = stitch sequence. The first object is stitched first. */
  objects: EmbObject[];
}

/** Default parameter values, applied wherever a param is omitted. */
export const DEFAULT_PARAMS: Required<EmbObjectParams> = {
  stitchLength: 2.5,
  beanRepeats: 0,
  raw: false,
  density: 0.30,
  fillStitchLength: 4,
  angle: 0,
  directionDeg: null,
  flowPath: null,
  underlay: true,
  underlayWeight: "auto",
  pullComp: 0.2,
  pushComp: 0.2,
  outline: true,
  fillStyle: "tatami",
  lineArt: false,
  blendColorId: "",
  motif: "wave",
  motifSizeMm: 4,
  carve: "none",
  motifRun: "none",
  applique: false,
};

/** Resolve an object's params against the defaults for the engine. */
export function resolveParams(
  type: StitchType,
  params: EmbObjectParams,
): Required<EmbObjectParams> {
  return {
    stitchLength: params.stitchLength ?? DEFAULT_PARAMS.stitchLength,
    beanRepeats: params.beanRepeats ?? DEFAULT_PARAMS.beanRepeats,
    raw: params.raw ?? DEFAULT_PARAMS.raw,
    density: params.density ?? DEFAULT_PARAMS.density,
    fillStitchLength: params.fillStitchLength ?? DEFAULT_PARAMS.fillStitchLength,
    angle: params.angle ?? DEFAULT_PARAMS.angle,
    directionDeg: params.directionDeg ?? DEFAULT_PARAMS.directionDeg,
    flowPath: params.flowPath ?? DEFAULT_PARAMS.flowPath,
    // running stitch never has underlay regardless of stored value
    underlay:
      type === "running" ? false : (params.underlay ?? DEFAULT_PARAMS.underlay),
    underlayWeight: params.underlayWeight ?? DEFAULT_PARAMS.underlayWeight,
    pullComp: params.pullComp ?? DEFAULT_PARAMS.pullComp,
    pushComp: params.pushComp ?? DEFAULT_PARAMS.pushComp,
    outline: params.outline ?? DEFAULT_PARAMS.outline,
    fillStyle: params.fillStyle ?? DEFAULT_PARAMS.fillStyle,
    lineArt: params.lineArt ?? DEFAULT_PARAMS.lineArt,
    blendColorId: params.blendColorId ?? DEFAULT_PARAMS.blendColorId,
    motif: params.motif ?? DEFAULT_PARAMS.motif,
    motifSizeMm: params.motifSizeMm ?? DEFAULT_PARAMS.motifSizeMm,
    carve: params.carve ?? DEFAULT_PARAMS.carve,
    motifRun: params.motifRun ?? DEFAULT_PARAMS.motifRun,
    applique: params.applique ?? DEFAULT_PARAMS.applique,
  };
}
