// Vendors the *Latin* subset of the app's web fonts into public/fonts/ and
// generates src/fonts.css with self-hosted @font-face rules. This removes the
// only third-party request on initial page load (Google Fonts), reinforcing the
// "nothing leaves your machine" privacy promise and removing a render-blocking
// stylesheet. Run once and commit the result; re-run to refresh:
//   node scripts/fetch-fonts.mjs
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(__dirname, "../public/fonts");
const CSS_OUT = resolve(__dirname, "../src/fonts.css");

// A recent-Chrome UA makes Google Fonts return woff2 with the modern subset
// split (so we can pick just the `latin` block).
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// The families/weights/styles actually referenced by tailwind.config.js +
// index.css. Keep this in sync if the design system's fonts change.
const FAMILIES = [
  { family: "Anton", axes: "", weights: [400], italics: false },
  { family: "Oswald", axes: "wght@", weights: [400, 500, 600, 700], italics: false },
  { family: "Libre Franklin", axes: "wght@", weights: [400, 500, 600, 700, 800], italics: false },
  { family: "DM Serif Display", axes: "ital@", weights: [400], italics: true },
  { family: "Space Mono", axes: "wght@", weights: [400, 700], italics: false },
];

function cssUrl(family, axes, weights, italics) {
  const name = family.replace(/ /g, "+");
  let spec;
  if (axes === "ital@") {
    // DM Serif Display only ships weight 400; request upright + italic.
    spec = italics ? `${name}:ital@0;1` : `${name}`;
  } else if (axes === "wght@") {
    spec = `${name}:wght@${weights.join(";")}`;
  } else {
    spec = name;
  }
  return `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function fetchBin(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

// Split the Google CSS into individual @font-face blocks, each preceded by a
// /* subset */ comment. We keep only the `latin` subset.
function latinBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) {
    if (m[1] === "latin") blocks.push(m[2]);
  }
  return blocks;
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const out = [
    "/* AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.",
    "   Self-hosted Latin subsets of the app's web fonts. */",
    "",
  ];
  // Variable fonts (Oswald, Libre Franklin) return ONE file covering a weight
  // range but Google emits a separate @font-face per requested weight pointing
  // at the same URL — so dedupe by source URL to store each file only once.
  const byUrl = new Map();

  for (const f of FAMILIES) {
    const css = await fetchText(cssUrl(f.family, f.axes, f.weights, f.italics));
    const blocks = latinBlocks(css);
    if (!blocks.length) throw new Error(`No latin block for ${f.family}`);

    for (const block of blocks) {
      const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || "400";
      const style = (block.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || "normal";
      const src = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
      if (!src) throw new Error(`No woff2 url in block for ${f.family}`);

      let fileName = byUrl.get(src);
      if (!fileName) {
        const bin = await fetchBin(src);
        const hash = createHash("sha1").update(bin).digest("hex").slice(0, 8);
        fileName = `${slug(f.family)}-${hash}.woff2`;
        await writeFile(resolve(FONT_DIR, fileName), bin);
        byUrl.set(src, fileName);
        console.log(`  ${f.family} ${weight} ${style} -> ${fileName} (${bin.length} bytes)`);
      } else {
        console.log(`  ${f.family} ${weight} ${style} -> ${fileName} (reused)`);
      }

      const unicode = (block.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim();
      out.push("@font-face {");
      out.push(`  font-family: "${f.family}";`);
      out.push(`  font-style: ${style};`);
      out.push(`  font-weight: ${weight};`);
      out.push("  font-display: swap;");
      out.push(`  src: url("/fonts/${fileName}") format("woff2");`);
      if (unicode) out.push(`  unicode-range: ${unicode};`);
      out.push("}");
      out.push("");
    }
  }

  await writeFile(CSS_OUT, out.join("\n"));
  console.log(`\nWrote ${CSS_OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
